### ISSUE TITLE
URL with index.php causes nginx 404

### ISSUE THREAD

**Issue by ghost** [perusio/drupal-with-nginx#37]
If I manually type the URL with trailing \index.php I get an nginx 404

e.g. http://www.site.com/index.php 

The index.php is set to internal, but can this be redirected to http://www.site.com for non-internal?

**Comment by hkirsman** [comment]
I'm trying to use elFinder in Drupal and it's trying to access /index.php?q=elfinder&app=ckeditor&CKEditor=edi so I get 404. Could you still hint me/us where I could fix that in nginx config?

**Comment by hkirsman** [comment]
Found it at apps/drupal/drupal.conf. My changes in diff:
-## Any other attempt to access PHP files returns a 404.
+## Allow accessing index.php files directly.
 location ~* ^.+\.php$ {
-    return 404;
+    ## Include the FastCGI config.
+    include apps/drupal/fastcgi_drupal.conf;
+    fastcgi_pass phpcgi;
 }

**Comment by emesch** [comment]
hkirsman, this issue is almost four years old.  You might get a better response by opening a new thread here, or checking out the nginx group on d.o.

I would look into why the url is "/index.php?q=elfinder&[...]" instead of "/elfinder?[...]".  The latter should work with perusio's config.

Your solution allows php files to be run by anyone under your web root which is generally not a good idea.  If you can't fix the url itself, you can write a much more restrictive location block that only passes to fastcgi if your url parameters are present.
